package Models;
// Generated 11-16-2016 12:49:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private BigDecimal idcategoria;
     private String nombrecategoria;
     private Set subcategorias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal idcategoria, String nombrecategoria) {
        this.idcategoria = idcategoria;
        this.nombrecategoria = nombrecategoria;
    }
    public Categoria(BigDecimal idcategoria, String nombrecategoria, Set subcategorias) {
       this.idcategoria = idcategoria;
       this.nombrecategoria = nombrecategoria;
       this.subcategorias = subcategorias;
    }
   
    public BigDecimal getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(BigDecimal idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombrecategoria() {
        return this.nombrecategoria;
    }
    
    public void setNombrecategoria(String nombrecategoria) {
        this.nombrecategoria = nombrecategoria;
    }
    public Set getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set subcategorias) {
        this.subcategorias = subcategorias;
    }




}


